platform:ios, '7.0'
pod "AFNetworking",     "~> 2.3.1"
pod "ASIHTTPRequest",   "~> 1.8.2"
pod "SBJson",           "~> 4.0.1"
pod "SHLineGraphView",  "~> 1.0.6"
pod "TBXML",            "~> 1.5"
pod "EGOTableViewPullRefreshAndLoadMore", "~> 1.0.4"
pod "PEPhotoCropEditor", "~> 1.3.1"
pod "MBProgressHUD", "~> 0.9"
pod "FXBlurView", "~> 1.6.2"
pod "EAIntroView", "~> 2.6.3"